### ISSUE TITLE
Node app crashes when apn is required [Windows]

### ISSUE THREAD

**Issue by drulia** [node-apn/node-apn#493]
Hello,

Application consisting of nothing else but this `var apn = require('apn');` in the `index.js` file, crashes right away on start with this:
```
...\node_modules\apn\lib\protocol\endpoint.js:17
const CLIENT_PRELUDE = Buffer.from("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");
                              ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> ...\node_modules\apn\lib\protocol\endpoint.js:17:31)
    ...
    at Module._compile (module.js:413:34)
```

I'm trying to run it on windows 10, is this not suppose to work on windows or there is some issue?

Edit:
Running on Node v5.6.0

**Comment by zaumreit** [comment]
@drulia I run this module on windows 10 as well and it works well. I think it might be relevant to node version, since Buffer.from is a new introduced API and has not been supported in node v5.6.0. You should upgrade your node to a higher version.

FYI: [node v5.6.0 buffer](https://nodejs.org/docs/v5.6.0/api/buffer.html)

**Comment by oliversalzburg** [comment]
Hmm, if `Buffer.from` was introduced in v6, then the `engine` in the `package.json` should reflect that requirement.

**Comment by zaumreit** [comment]
@oliversalzburg I think so. 
BTW [node v5.12.0](https://nodejs.org/docs/latest-v5.x/api/buffer.html) has supported.

**Comment by drulia** [comment]
yep, upgrading to v6.9.2 has fixed the issue.
And yes, I can confirm as well that it is working v5.12.0 on ubuntu at least.
