### ISSUE TITLE
Can you change the http2 dependency to use npm?

### ISSUE THREAD

**Issue by xuduo** [node-apn/node-apn#582]
in package.json:
"http2": "https://github.com/node-apn/node-http2/archive/apn-2.1.4.tar.gz"

I'm having some troble downloading from China.

**Comment by florianreinhart** [comment]
Is github blocked in China?

**Comment by xuduo** [comment]
some of my servers might have trouble sometime, who knows.
Connecting foreign server is always unreliable.
npm is ok , we have mirror sites in China.

**Comment by florianreinhart** [comment]
We use a fork of the node-http2 module with some additional bug fixes. node-http2 seems to be unmaintained, that's why we had to create a fork.

However, I don't want to publish that fork on npm. You could create a fork of node-apn, host the apn-2.1.4.tar.gz file somewhere else and point to that in the package.json.

**Comment by xuduo** [comment]
ok
